name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Version of Rust and Cargo
      run: rustc --version && cargo --version

    - name: Build
      run: cargo build --workspace --locked --verbose

    - name: Test
      run: cargo test --workspace --locked --verbose

  security-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: rustsec/audit-check@v1.4.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Install cargo-deb
      run: cargo install cargo-deb --locked

    - name: Build
      run: cargo build --locked --release --all --verbose

    - name: Package as deb file
      run: cargo deb --no-build --verbose

    - name: Upload Artifact Linux
      uses: actions/upload-artifact@v4
      with:
        name: synapse_sycli
        path: |
          target/release/synapse
          target/release/sycli

    - name: Upload Artifact Linux as .deb package
      uses: actions/upload-artifact@v4
      with:
        name: synapse_deb
        path: target/debian/*.deb
